# Configuración general
spring.application.name=E-Commerce_Platform

# Conexión a base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1

# Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Validaciones y seguridad (opcional)
server.error.include-message=always
